/**
 * The list of `.inc` filenames shipped with the AMX Mod X distribution. Used to
 * decide whether a `#include` should be rendered as a document link pointing to
 * the online API reference (`https://amxmodx.org/api/<name>`).
 *
 * @example
 * amxmodxDefaultHeaders.includes('amxmodx'); // true
 * amxmodxDefaultHeaders.includes('unknown'); // false
 */
export const amxmodxDefaultHeaders: readonly string[] = [
    'amxconst',
    'amxmisc',
    'amxmodx',
    'amxmodx_version',
    'cellarray',
    'cellstack',
    'celltrie',
    'core',
    'csstats',
    'cstrike',
    'csx',
    'cvars',
    'datapack',
    'dbi',
    'dodconst',
    'dodfun',
    'dodstats',
    'dodx',
    'engine',
    'engine_const',
    'engine_stocks',
    'esf',
    'esf_const',
    'fakemeta',
    'fakemeta_const',
    'fakemeta_stocks',
    'fakemeta_util',
    'file',
    'float',
    'fun',
    'geoip',
    'hamsandwich',
    'ham_const',
    'hlsdk_const',
    'lang',
    'messages',
    'message_const',
    'message_stocks',
    'newmenus',
    'ns',
    'ns2amx',
    'ns_const',
    'nvault',
    'regex',
    'sockets',
    'sorting',
    'sqlx',
    'string',
    'textparse_ini',
    'textparse_smc',
    'tfconst',
    'tfcstats',
    'tfcx',
    'time',
    'tsconst',
    'tsfun',
    'tsstats',
    'tsx',
    'vault',
    'vector',
    'xs',
];
